name: Deploy

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  unit:
    name: Run Deploy Github Pages 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run deploy